Update Dockerfile

diff --git a/fd.ficohsa.ach.configurator.ui/Dockerfile b/fd.ficohsa.ach.configurator.ui/Dockerfile
--- a/fd.ficohsa.ach.configurator.ui/Dockerfile
+++ b/fd.ficohsa.ach.configurator.ui/Dockerfile
@@ -7,20 +7,10 @@ WORKDIR /app
 # Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 RUN \
-  if [ -f package-lock.json ]; then 
-    npm install sharp;
-  elif [ -f yarn.lock ]; then
-    yarn --frozen-lockfile;
-  elif [ -f pnpm-lock.yaml ]; then
-    yarn global add pnpm && pnpm i --frozen-lockfile;
-else
-  echo "Lockfile not found. You may need to choose a package manager." && exit 1;
-fi
-
-  #if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  #elif [ -f package-lock.json ]; then npm ci; \
-  #elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-  #else echo "Lockfile not found." && exit 1; \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
   fi
 
 
